# Generated by Django 4.1.6 on 2023-03-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.SlugField(max_length=255),
        ),
    ]
