# Generated by Django 4.1.6 on 2023-03-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_slug_title_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug_title',
            field=models.SlugField(blank=True),
        ),
    ]
